build.gradle, src/main/java/com/potato/ecommerce/ECommerceApplication.java, src/main/java/com/potato/ecommerce/domain/cart/entity/CartEntity.java, src/main/java/com/potato/ecommerce/domain/cartProduct/controller/CartProductController.java, src/main/java/com/potato/ecommerce/domain/cartProduct/entity/CartProductEntity.java, src/main/java/com/potato/ecommerce/domain/category/entity/CategoryEntity.java, src/main/java/com/potato/ecommerce/domain/favorite/controller/FavoriteController.java, src/main/java/com/potato/ecommerce/domain/favorite/entity/FavoriteEntityId.java, src/main/java/com/potato/ecommerce/domain/member/entity/MemberEntity.java, src/main/java/com/potato/ecommerce/domain/order/entity/OrderEntity.java, src/main/java/com/potato/ecommerce/domain/payment/entity/PaymentEntity.java, src/main/java/com/potato/ecommerce/domain/payment/vo/PaymentMethod.java, src/main/java/com/potato/ecommerce/domain/product/controller/ProductController.java, src/main/java/com/potato/ecommerce/domain/product/entity/ProductEntity.java, src/main/java/com/potato/ecommerce/domain/receiver/controller/ReceiverController.java, src/main/java/com/potato/ecommerce/domain/receiver/entity/ReceiverEntity.java, src/main/java/com/potato/ecommerce/domain/revenue/controller/RevenueController.java, src/main/java/com/potato/ecommerce/domain/revenue/dto/ResponseRevenue.java, src/main/java/com/potato/ecommerce/domain/revenue/entity/RevenueEntity.java, src/main/java/com/potato/ecommerce/domain/revenue/model/Revenue.java, src/main/java/com/potato/ecommerce/domain/revenue/repository/RevenueRepository.java, src/main/java/com/potato/ecommerce/domain/revenue/service/RevenueService.java, src/main/java/com/potato/ecommerce/domain/store/controller/StoreController.java, src/main/java/com/potato/ecommerce/domain/store/entity/StoreEntity.java, src/main/java/com/potato/ecommerce/domain/store/model/Store.java, src/main/java/com/potato/ecommerce/global/jwt/JwtUtil.java
=> Feat/revenue 사업자 번호 발급 구현

src/main/java/com/potato/ecommerce/domain/member/model/Member.java, src/main/java/com/potato/ecommerce/domain/receiver/controller/ReceiverController.java, src/main/java/com/potato/ecommerce/domain/receiver/dto/ReceiverForm.java, src/main/java/com/potato/ecommerce/domain/receiver/entity/ReceiverEntity.java, src/main/java/com/potato/ecommerce/domain/receiver/model/Receiver.java, src/main/java/com/potato/ecommerce/domain/receiver/repository/ReceiverJpaRepository.java, src/main/java/com/potato/ecommerce/domain/receiver/repository/ReceiverRepository.java, src/main/java/com/potato/ecommerce/domain/receiver/repository/ReceiverRepositoryImpl.java, src/main/java/com/potato/ecommerce/domain/receiver/service/ReceiverService.java, src/main/java/com/potato/ecommerce/global/exception/ExceptionMessage.java
=> 배송지 등록, 조회, 수정 기능 구현

src/main/java/com/potato/ecommerce/domain/member/repository/MemberJpaRepository.java
=> JpaRepository 오타 수정

src/main/java/com/potato/ecommerce/domain/revenue/model/Revenue.java, src/main/java/com/potato/ecommerce/domain/revenue/repository/JpaRevenueRepository.java, src/main/java/com/potato/ecommerce/domain/revenue/repository/RevenueRepository.java, src/main/java/com/potato/ecommerce/domain/revenue/repository/RevenueRepositoryImpl.java, src/main/java/com/potato/ecommerce/domain/revenue/service/RevenueService.java, src/main/java/com/potato/ecommerce/domain/store/controller/StoreController.java, src/main/java/com/potato/ecommerce/domain/store/controller/StoreManagementController.java, src/main/java/com/potato/ecommerce/domain/store/dto/DeleteStoreRequest.java, src/main/java/com/potato/ecommerce/domain/store/dto/OrderAcceptResponse.java, src/main/java/com/potato/ecommerce/domain/store/dto/StoreRequest.java, src/main/java/com/potato/ecommerce/domain/store/entity/StoreEntity.java, src/main/java/com/potato/ecommerce/domain/store/model/Store.java, src/main/java/com/potato/ecommerce/domain/store/repository/JpaStoreRepository.java, src/main/java/com/potato/ecommerce/domain/store/repository/StoreRepository.java, src/main/java/com/potato/ecommerce/domain/store/repository/StoreRepositoryImpl.java, src/main/java/com/potato/ecommerce/domain/store/service/StoreManagementService.java, src/main/java/com/potato/ecommerce/domain/store/service/StoreService.java
=> Feat/store JpaRepository 추상화, 검증 로직 객체로 책임 이전

src/main/java/com/potato/ecommerce/domain/category/entity/CategoryEntity.java, src/main/java/com/potato/ecommerce/domain/product/controller/ProductController.java, src/main/java/com/potato/ecommerce/domain/product/dto/ProductRequest.java, src/main/java/com/potato/ecommerce/domain/product/dto/ProductResponse.java, src/main/java/com/potato/ecommerce/domain/product/dto/ProductSimpleResponse.java, src/main/java/com/potato/ecommerce/domain/product/entity/ProductEntity.java, src/main/java/com/potato/ecommerce/domain/product/model/Product.java, src/main/java/com/potato/ecommerce/domain/product/service/ProductService.java
=> :sparkles: product 상품 등록 기능 구현

src/main/java/com/potato/ecommerce/domain/product/dto/ProductListResponse.java, src/main/java/com/potato/ecommerce/domain/product/repository/ProductQueryRepository.java, src/main/java/com/potato/ecommerce/domain/product/repository/ProductQueryRepositoryImpl.java, src/main/java/com/potato/ecommerce/domain/store/controller/StoreController.java, src/main/java/com/potato/ecommerce/domain/store/controller/StoreManagementController.java, src/main/java/com/potato/ecommerce/domain/store/entity/StoreEntity.java, src/main/java/com/potato/ecommerce/domain/store/service/StoreManagementService.java, src/main/java/com/potato/ecommerce/global/config/querydsl/QuerydslConfiguration.java, src/main/java/com/potato/ecommerce/global/util/RestPage.java
등록한 상품 목록 조회 API 구현(paging, Querydsl)
어떤 변경 사항이 있나요?
=> Feat/store 등록한 상품 목록 조회 API 구현(paging, Querydsl)

src/main/java/com/potato/ecommerce/domain/product/controller/ProductController.java, src/main/java/com/potato/ecommerce/domain/product/entity/ProductEntity.java, src/main/java/com/potato/ecommerce/domain/product/model/Product.java, src/main/java/com/potato/ecommerce/domain/product/service/ProductService.java, src/main/java/com/potato/ecommerce/global/jwt/interceptor/InterceptorConfig.java
=> Feat/product is_deleted 칼럼명 수정, 조회 API URL 수정

src/main/java/com/potato/ecommerce/domain/store/service/StoreService.java, src/main/java/com/potato/ecommerce/global/config/JpaConfig.java, src/main/java/com/potato/ecommerce/global/config/redis/RedisCacheConfig.java, src/main/java/com/potato/ecommerce/global/config/redis/RedisConfig.java
redis 설정 파일, store 상품 조회 캐싱
어떤 변경 사항이 있나요?
=> Feat/store redis 설정 파일, store 상품 조회 캐싱

src/main/java/com/potato/ecommerce/domain/cart/controller/CartController.java, src/main/java/com/potato/ecommerce/domain/cart/repository/CartRepository.java, src/main/java/com/potato/ecommerce/domain/cart/service/CartService.java
=> :recycle: 장바구니 삭제, 목록 조회 기능 수정

src/main/java/com/potato/ecommerce/domain/store/controller/StoreController.java, src/main/java/com/potato/ecommerce/domain/store/dto/DeleteStoreRequest.java, src/main/java/com/potato/ecommerce/domain/store/dto/LoginRequest.java, src/main/java/com/potato/ecommerce/domain/store/dto/StoreRequest.java, src/main/java/com/potato/ecommerce/domain/store/dto/UpdateStoreRequest.java, src/main/java/com/potato/ecommerce/domain/store/repository/StoreRepositoryImpl.java, src/main/java/com/potato/ecommerce/domain/store/service/StoreService.java, src/test/java/com/potato/ecommerce/domain/store/StoreServiceTest.java, src/test/java/com/potato/ecommerce/domain/store/StoreTest.java, src/test/java/com/potato/ecommerce/domain/store/StoreTestUtil.java
StoreService, Store 테스트 코드 작성
어떤 변경 사항이 있나요?
=> Feat/store test StoreService, Store 테스트 코드 작성

src/main/java/com/potato/ecommerce/domain/revenue/controller/RevenueController.java, src/main/java/com/potato/ecommerce/domain/revenue/entity/RevenueEntity.java, src/main/java/com/potato/ecommerce/domain/revenue/message/RevenueMessage.java, src/main/java/com/potato/ecommerce/domain/revenue/model/Revenue.java, src/main/java/com/potato/ecommerce/domain/revenue/repository/RevenueRepositoryImpl.java, src/main/java/com/potato/ecommerce/domain/store/controller/StoreController.java, src/main/java/com/potato/ecommerce/domain/store/entity/StoreEntity.java, src/main/java/com/potato/ecommerce/domain/store/message/StoreMessage.java, src/main/java/com/potato/ecommerce/domain/store/model/Store.java, src/main/java/com/potato/ecommerce/domain/store/repository/StoreRepositoryImpl.java, src/main/java/com/potato/ecommerce/domain/store/service/StoreService.java, src/main/java/com/potato/ecommerce/global/exception/ExceptionMessage.java
=> Feat/store 코드 스타일 통일화

src/main/java/com/potato/ecommerce/domain/mail/message/MailMessage.java, src/main/java/com/potato/ecommerce/domain/mail/service/MailService.java, src/main/java/com/potato/ecommerce/domain/member/controller/MemberController.java, src/main/java/com/potato/ecommerce/domain/member/entity/MemberEntity.java, src/main/java/com/potato/ecommerce/domain/member/message/MemberMessage.java, src/main/java/com/potato/ecommerce/domain/member/model/Member.java, src/main/java/com/potato/ecommerce/domain/member/repository/MemberRepository.java, src/main/java/com/potato/ecommerce/domain/member/repository/MemberRepositoryImpl.java, src/main/java/com/potato/ecommerce/domain/member/service/MemberService.java, src/main/java/com/potato/ecommerce/domain/receiver/controller/ReceiverController.java, src/main/java/com/potato/ecommerce/domain/receiver/message/ReceiverMessage.java
=> Member 도메인 코드 통일

src/main/java/com/potato/ecommerce/domain/revenue/controller/RevenueController.java, src/main/java/com/potato/ecommerce/domain/revenue/entity/RevenueEntity.java, src/main/java/com/potato/ecommerce/domain/revenue/message/RevenueMessage.java, src/main/java/com/potato/ecommerce/domain/revenue/service/RevenueService.java, src/main/java/com/potato/ecommerce/domain/store/controller/StoreController.java, src/main/java/com/potato/ecommerce/domain/store/dto/StoreRequest.java, src/main/java/com/potato/ecommerce/domain/store/dto/StoreResponse.java, src/main/java/com/potato/ecommerce/domain/store/dto/UpdateStoreRequest.java, src/main/java/com/potato/ecommerce/domain/store/entity/StoreEntity.java, src/main/java/com/potato/ecommerce/domain/store/message/StoreMessage.java, src/main/java/com/potato/ecommerce/domain/store/service/StoreService.java, src/test/java/com/potato/ecommerce/domain/store/StoreServiceTest.java
사업자 번호 AtomicLong 으로 수정, create response 객체 반환하도록 변경, request dto 패턴 누락 수정
어떤 변경 사항이 있나요?
=> Feat/store refector 사업자 번호 AtomicLong 으로 수정, create response 객체 반환하도록 변경, request dto 패턴 누락 수정

src/main/java/com/potato/ecommerce/domain/store/controller/StoreController.java, src/main/java/com/potato/ecommerce/domain/store/service/StoreService.java
store create 반환 값 response -> id 로 수정
어떤 변경 사항이 있나요?
=> :recycle: store create 반환 값 response -> id 로 수정

src/main/java/com/potato/ecommerce/domain/category/entity/CategoryEntity.java, src/main/java/com/potato/ecommerce/domain/category/entity/CategoryType.java, src/main/java/com/potato/ecommerce/domain/category/repository/CategoryRepository.java, src/main/java/com/potato/ecommerce/domain/category/service/CategoryService.java
=> :recycle: 카테고리 코드 리팩토링

src/main/java/com/potato/ecommerce/domain/order/controller/dto/response/OrderInfoResponseDTO.java, src/main/java/com/potato/ecommerce/domain/order/controller/dto/response/OrderInfoWithHistoryResponseDTO.java, src/main/java/com/potato/ecommerce/domain/order/dto/OrderInfo.java, src/main/java/com/potato/ecommerce/domain/order/dto/OrderInfoWithHistory.java, src/main/java/com/potato/ecommerce/domain/order/entity/OrderEntity.java, src/main/java/com/potato/ecommerce/domain/order/service/OrderService.java
=> Lazy Entity 문제 해결, Dto 내부 Entity -> Dto로 변환

src/main/java/com/potato/ecommerce/domain/category/repository/ProductCategoryRepository.java, src/main/java/com/potato/ecommerce/domain/product/controller/ProductController.java, src/main/java/com/potato/ecommerce/domain/product/dto/ProductRequest.java, src/main/java/com/potato/ecommerce/domain/product/dto/ProductResponse.java, src/main/java/com/potato/ecommerce/domain/product/dto/ProductUpdateRequest.java, src/main/java/com/potato/ecommerce/domain/product/entity/ProductEntity.java, src/main/java/com/potato/ecommerce/domain/product/repository/ProductRepository.java, src/main/java/com/potato/ecommerce/domain/product/service/ProductService.java
=> Feat/product 코드 리팩토링

src/main/java/com/potato/ecommerce/domain/product/repository/ProductQueryRepositoryImpl.java
=> :recycle: querydsl 수정

src/main/java/com/potato/ecommerce/domain/member/controller/MemberController.java, src/main/java/com/potato/ecommerce/domain/member/entity/MemberEntity.java, src/main/java/com/potato/ecommerce/domain/member/service/MemberService.java, src/main/java/com/potato/ecommerce/global/jwt/interceptor/AuthInterceptor.java
=> 회원 탈퇴 기능 구현

src/main/java/com/potato/ecommerce/domain/product/dto/ProductDetailResponse.java, src/main/java/com/potato/ecommerce/domain/product/dto/ShopProductResponse.java, src/main/java/com/potato/ecommerce/domain/product/service/ProductService.java
=> :recycle: Response 반환 추가

src/main/java/com/potato/ecommerce/domain/product/dto/ProductListResponse.java
projection error 해결 -> ProductListResponse 기본 생성자 추가
어떤 변경 사항이 있나요?
=> :sparkles: projection error 해결 -> ProductListResponse 기본 생성자 추가

src/main/java/com/potato/ecommerce/domain/store/controller/StoreController.java, src/main/java/com/potato/ecommerce/domain/store/service/StoreService.java, src/test/java/com/potato/ecommerce/domain/store/StoreServiceTest.java
정책 변경에 따른 Store Test 코드 수정
어떤 변경 사항이 있나요?
=> Feat/store refector 정책 변경에 따른 Store Test 코드 수정

src/main/java/com/potato/ecommerce/domain/product/controller/ProductController.java, src/main/java/com/potato/ecommerce/domain/product/repository/ProductRepository.java, src/main/java/com/potato/ecommerce/domain/product/service/ProductService.java, src/main/java/com/potato/ecommerce/domain/store/dto/ProductOfStoreResponse.java, src/main/java/com/potato/ecommerce/global/jwt/interceptor/InterceptorConfig.java
product store 조회 API 구현
어떤 변경 사항이 있나요?
=> Feat/product store product store 조회 API 구현

src/main/java/com/potato/ecommerce/domain/product/controller/ProductController.java, src/main/java/com/potato/ecommerce/domain/product/dto/ProductDetailResponse.java, src/main/java/com/potato/ecommerce/domain/product/dto/ProductResponse.java, src/main/java/com/potato/ecommerce/domain/product/repository/ProductQueryRepositoryImpl.java, src/main/java/com/potato/ecommerce/domain/product/repository/ProductRepository.java, src/main/java/com/potato/ecommerce/domain/product/service/ProductService.java, src/main/java/com/potato/ecommerce/domain/store/dto/StoreResponse.java
=> :recycle: findProductDetail Response 반환 추가

src/main/java/com/potato/ecommerce/domain/product/dto/ProductSimpleResponse.java, src/main/java/com/potato/ecommerce/domain/product/dto/ShopProductResponse.java
=> :recycle: ProductSimpleResponse, ShopProductResponse Response 반환 추가

src/main/java/com/potato/ecommerce/domain/member/controller/MemberController.java, src/main/java/com/potato/ecommerce/domain/member/dto/ResponseSignInDto.java, src/main/java/com/potato/ecommerce/domain/store/controller/StoreController.java, src/main/java/com/potato/ecommerce/global/jwt/JwtUtil.java, src/main/java/com/potato/ecommerce/global/jwt/interceptor/AuthInterceptor.java
=> 토큰 전달 방식 변경

src/main/java/com/potato/ecommerce/domain/product/controller/ProductController.java, src/main/java/com/potato/ecommerce/domain/product/entity/ProductEntity.java, src/main/java/com/potato/ecommerce/domain/revenue/controller/RevenueController.java, src/main/java/com/potato/ecommerce/domain/store/controller/StoreController.java, src/main/java/com/potato/ecommerce/domain/store/dto/ProductOfStoreResponse.java
URL 수정, createdAt 버그 수정
어떤 변경 사항이 있나요?
=> Feat/product refector URL 수정, createdAt 버그 수정

build.gradle, script.js, src/main/java/com/potato/ecommerce/global/jwt/interceptor/InterceptorConfig.java
=> Feat/management 모니터링 툴 적용

src/main/java/com/potato/ecommerce/domain/member/dto/SignUpDto.java, src/main/java/com/potato/ecommerce/global/exception/GlobalExceptionHandler.java
=> feat/member validation 메시지 추가 및 validExceptionHandler 반환 타입 변경

src/main/java/com/potato/ecommerce/domain/receiver/dto/ReceiverForm.java, src/main/java/com/potato/ecommerce/global/jwt/interceptor/AuthInterceptor.java
=> Feat/receiver Cors 해결 및 ResponseDTO id필드 추가

src/main/java/com/potato/ecommerce/domain/receiver/controller/ReceiverController.java, src/main/java/com/potato/ecommerce/domain/receiver/service/ReceiverService.java
=> feat/receiver 주소 단일 조회 기능 추가

src/main/java/com/potato/ecommerce/domain/product/dto/ProductDetailResponse.java
=> :recycle: ProductDetailResponse id 반환 수정

src/main/java/com/potato/ecommerce/domain/order/controller/OrderController.java, src/main/java/com/potato/ecommerce/domain/order/repository/history/HistoryJpaRepository.java, src/main/java/com/potato/ecommerce/domain/order/service/HistoryService.java, src/main/java/com/potato/ecommerce/domain/order/service/OrderService.java, src/main/java/com/potato/ecommerce/global/exception/GlobalExceptionHandler.java
=> :recycle: orderComplete, Cancel param 수정

src/main/java/com/potato/ecommerce/domain/payment/service/TossService.java
배포 과정에서 ":" 를 못읽는 문제 해결
어떤 변경 사항이 있나요?
=> :recycle: 배포 과정에서 ":" 를 못읽는 문제 해결
